temperature: 1.0
max_tokens: 128
top_p: 1.0
model_name: "/home/v_rahimzadeh/hf_models/models--microsoft--Phi-4-mini-instruct/snapshots/d02e859785d6a6ee7cb2ed7913e32b7a0e8665b4"
api_provider: "localhost"