defaults:
  - backstories: test
  - human_survey_data: ATP_W92_distribution_all
  - _self_

# Set the output directory
hydra:
  run:
    dir: outputs/demo_filtering/${now:%Y-%m-%d}/${now:%H-%M-%S}

run_dir: ${hydra:runtime.output_dir}
save_dir: /home/v_rahimzadeh/impersonation/generate_backstories/process_and_generate_two_step/forked_anthology/anthology/outputs/demographics_matching

demographics_survey_path: /home/v_rahimzadeh/impersonation/generate_backstories/process_and_generate_two_step/forked_anthology/anthology/outputs/demographics_survey/d02e859785d6a6ee7cb2ed7913e32b7a0e8665b4_demographics_survey_2025-04-13_15-08-56.pkl
human_survey_path: /home/v_rahimzadeh/impersonation/generate_backstories/ATP/W92_Jul21/ATP W92.sav
demographics_info_path: /home/v_rahimzadeh/impersonation/generate_backstories/process_and_generate_two_step/forked_anthology/data/questions/ATP_W92_demographic_questions.json
# output data name
output_data_name: test_forked
matching_method: greedy
wave: 92
# Debugging mode
debug: false


trait_of_interest:
  - age_category_4
  - gender
  - education_level
  - income_level_category_13
  - race

# random seed
random_seed: 42

# Hyperparameters
optimization_parameters:
  k_list: [500,1000,1500,2000,2500,3000,3500,4000]
  beta_config: # log-uniform distribution
    start: -5
    stop: 0
    num: 5
    base: 2
  loss_type: "l2"
  lr: 0.01
  max_iter: 10000
  verbose: true
  order: 2