defaults:
  - backstories: test
  - questionnaire/ATP: ATP_W92_questions
  - special_prompt: consistency_prompt
  - format/mcq_symbol: uppercase
  - format/choice_format: curved_bracket
  - format/surveyor_respondent: question_answer
  - llm_parameters: phi_4
  - _self_

# Set the output directory
hydra:
  run:
    dir: outputs/ATP_W${wave}/${now:%Y-%m-%d}/${now:%H-%M-%S}

run_dir: ${hydra:runtime.output_dir}
save_dir: /home/v_rahimzadeh/impersonation/generate_backstories/process_and_generate_two_step/forked_anthology/anthology/outputs/ATP_W${wave}

# output data name
output_time_stamp: ${now:%Y-%m-%d}_${now:%H-%M-%S}
output_data_name: forked_test

# Debugging mode
debug: false

# Parallelization parameter
num_processes: 10

# The seed to use for the random number generator
random_seed: 42

# Frequency of saving the generated backstories
freq: 5

wave: 92

include_compliance_forcing: true
number_compliance_forcing: 100

# configuration for baseline survey
is_baseline: false
survey_data_path: # Download from Pew Research Center. The data file format should be sav.
survey_demographics_metadata_path: data/questions/ATP_W${wave}_demographic_questions.json
prompt_style: qa
trait_of_interest:
  - income
  - race
  - age
  - gender
  - education
include_answer_forcing: true # this answer forcing is answer forcing in baseline prompt, not in survey prompt