defaults:
  - backstories: test
  - questionnaire/party_affiliation: party_affiliation_questions
  - special_prompt: consistency_prompt
  - format/mcq_symbol: uppercase
  - format/choice_format: curved_bracket
  - format/surveyor_respondent: question_answer
  - llm_parameters: phi_4
  - _self_

# number of samples to obtain for each questionnaire
num_sample_response: 40

# Set the output directory
hydra:
  run:
    dir: outputs/political_affiliation/${now:%Y-%m-%d}/${now:%H-%M-%S}

run_dir: ${hydra:runtime.output_dir}
save_dir: /home/v_rahimzadeh/impersonation/generate_backstories/process_and_generate_two_step/forked_anthology/anthology/outputs/political_affiliation

# output data name
output_data_name: forked_test

# Debugging mode
debug: false

# Parallelization parameter
num_processes: 1

# The seed to use for the random number generator
random_seed: 42

# Frequency of saving the generated backstories
freq: 5