backstory_path: /home/v_rahimzadeh/impersonation/generate_backstories/process_and_generate_two_step/forked_anthology/outputs/self_generated_backstories/2025-04-13/14-33-52/d02e859785d6a6ee7cb2ed7913e32b7a0e8665b4_generated_backstory_fork_test.csv
backstory_type: test
num_backstories: -1
shuffle: False