defaults:
  - self_generate: self_generate
  - llm_parameters: phi_4
  - _self_

# Set the output directory
hydra:
  run:
    dir: outputs/self_generated_backstories/${now:%Y-%m-%d}/${now:%H-%M-%S}

run_dir: ${hydra:runtime.output_dir}
save_dir: /home/v_rahimzadeh/impersonation/generate_backstories/process_and_generate_two_step/forked_anthology/anthology/outputs/self_generated_backstories
num_backstories: 2
num_processes: 4
freq: 10
# Replace this with the name of the experiment
# output_data_name: ${now:%Y-%m-%d}_${now:%H-%M-%S}
output_data_name: fork_test

debug: false
